# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI with Gradle

on:
  push:
    branches: [ "kotlin" ]
  pull_request:
    branches: [ "kotlin" ]
  workflow_dispatch:

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Gradle Built
      uses: gradle/gradle-build-action@v2 # v2.6.0
      with:
        gradle-version: 8.4
    - name: dokkaHtml
      run: ./gradlew dokkaHtml
    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build/dokka/html # The folder the action should deploy.
